[versions]
agp = "8.10.1"
adhan2 = "0.0.5"
jetbrainsKotlinJvm = "2.2.20"
kotlin = "2.2.20"
coreKtx = "1.17.0"
kotlinxDatetime = "0.7.1"
lifecycleRuntimeKtx = "2.9.4"
composeBom = "2025.10.00"
activityCompose = "1.11.0"
koin-bom="4.1.1"
junitBom = "5.13.4"
junitVersion = "1.3.0"
kotlinxCoroutinesTest = "1.10.2"
assertjCore = "3.27.5"
mockk = "1.14.5"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
truth = "1.1.3"
turbine = "1.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertjCore" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

junit-bom-group = { group = "org.junit", name = "junit-bom", version.ref = "junitBom" }
junit-jupiter-api-group = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine-group = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-jupiter-params-group = { group = "org.junit.jupiter", name = "junit-jupiter-params" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBom" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-suite-api = { module = "org.junit.jupiter:junit-platform-suite-api" }
junit-platform-suite-engine = { module = "org.junit.jupiter:junit-platform-suite-engine" }


kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

adhan = { module = "com.batoulapps.adhan:adhan2", version.ref = "adhan2" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-android-viewmodel = { module = "io.insert-koin:koin-androidx-viewmodel" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose"}
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel"}
koin-compose-viewmodel-android = { module = "io.insert-koin:koin-compose-viewmodel-android"}
koin-test = { module = "io.insert-koin:koin-test" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
