[versions]
accompanistPermissions = "0.34.0"
agp = "8.10.1"
adhan2 = "0.0.6"
datastorePreferences = "1.1.7"
kotlinxSerializationJson = "1.8.1"
ksp = "2.2.20-2.0.3"
jetbrainsKotlinJvm = "2.2.20"
kotlin = "2.2.20"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
kotlinxDatetime = "0.7.1"
lifecycleRuntimeKtx = "2.9.4"
composeBom = "2025.10.00"
materialVersion = "1.9.4"
materialIcons = "1.7.8"
navigationCompose = "2.9.5"
activityCompose = "1.11.0"
composeCompiler = "2.0.3"
koin-bom="4.1.1"
koin-annotation = "2.3.0"
coil = "3.3.0"
okhttp = "4.12.0"

junitBom = "5.13.4"
junitVersion = "1.3.0"
junitPlatformSuiteEngine = "1.13.4"
kotlinxCoroutinesTest = "1.10.2"
assertjCore = "3.27.5"
mockk = "1.14.5"
espressoCore = "3.7.0"
playServicesLocation = "21.3.0"
truth = "1.1.3"
turbine = "1.2.1"
junit = "4.13.2"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertjCore" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIcons" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

adhan = { module = "com.batoulapps.adhan:adhan2", version.ref = "adhan2" }
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-android-viewmodel = { module = "io.insert-koin:koin-androidx-viewmodel" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose"}
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel"}
koin-compose-viewmodel-android = { module = "io.insert-koin:koin-compose-viewmodel-android"}
#koin-ksp = { module = "io.insert-koin:koin-ksp-compiler" }
#koin-annotations = { module = "io.insert-koin:koin-annotations"}

koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotation" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotation" }
#
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBom" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junitPlatformSuiteEngine"  }
platform-junit-platform-suite-engine = { module = "org.junit.platform:junit-platform-suite-engine", version.ref = "junitPlatformSuiteEngine" }
junit-platform-suite-api = { module = "org.junit.jupiter:junit-platform-suite-api" }
junit-platform-suite-engine = { module = "org.junit.jupiter:junit-platform-suite-engine" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
